version: '3.8'

services:
  dev:
    container_name: cronos_api_dev
    image: cronos_api_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - '7500:7500'
    networks:
      - cronos-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: cronos_api_prod
    image: cronos_api_prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - '7500:7500'
    networks:
      - cronos-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  cronos-network:
